{"name": "test_2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "login_first = None\n\n    def test_2(login_first):\n        print(\"用例222222222222\")\n>       assert 1==2\nE       assert 1 == 2\n\ncase\\test_repeat.py:25: AssertionError"}, "start": 1595582051577, "stop": 1595582051577, "uuid": "f25f58ac-d542-4493-85f9-71172766ef20", "historyId": "725ca383e94bc50971d38f4f36b6a784", "testCaseId": "1a912bc7a219142290fec87de98d7bc2", "fullName": "case.test_repeat#test_2", "labels": [{"name": "parentSuite", "value": "case"}, {"name": "suite", "value": "test_repeat"}, {"name": "host", "value": "pangchuan"}, {"name": "thread", "value": "15232-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test_repeat"}]}