{"name": "test_case4", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <case.test_allure_use.TestDemo object at 0x000001F786161B50>\n\n    @allure.story(\"用例3：xxxxxxxxxxxxx\")\n    def test_case4(self):\n        step_1()\n        step_3()\n>       assert  1==2\nE       assert 1 == 2\n\ncase\\test_allure_use.py:59: AssertionError"}, "start": 1595582050549, "stop": 1595582050552, "uuid": "0d39ce0f-e001-45b5-b791-182b3c326eb6", "historyId": "bf3ba79f5ae9c196446b727d883faedc", "testCaseId": "7ab551748199fe1de5c96e4ed6b1effc", "fullName": "case.test_allure_use.TestDemo#test_case4", "labels": [{"name": "story", "value": "用例3：xxxxxxxxxxxxx"}, {"name": "feature", "value": "功能点：编辑文章分类页面"}, {"name": "parentSuite", "value": "case"}, {"name": "suite", "value": "test_allure_use"}, {"name": "subSuite", "value": "TestDemo"}, {"name": "host", "value": "pangchuan"}, {"name": "thread", "value": "15232-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test_allure_use"}]}